backend:
  name: github
  repo: MeXaaR/f5communication

media_folder: static/assets
public_folder: /assets

collections: 
  - name: content
    label: Content
    files:
      - label: Team Section
        name: teamsection
        file: src/content/teamsection.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: subtitle, widget: markdown }
          - label: Members
            name: members
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Job, name: title, widget: string }
              - { label: Twitter, name: twitter, widget: string }
              - { label: LinkedIn, name: linkedin, widget: string }
              - { label: Photo, name: image, widget: image }
      - label: Third Section
        name: thirdsection
        file: src/content/thirdsection.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: subtitle, widget: markdown }
          - label: Partners
            name: partners
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Logo, name: logo, widget: image }
      - label: Second Section
        name: secondsection
        file: src/content/secondsection.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: subtitle, widget: markdown }
          - { label: Image, name: image, widget: image }
      - label: First Section
        name: firstsection
        file: src/content/firstsection.yml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Text, name: subtitle, widget: markdown }
          - label: Skills
            name: cards
            widget: list
            fields:
              - { label: Icon, name: icon, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: string }
